export const nflTeams = [
  "ARI",
  "ATL",
  "BAL",
  "BUF",
  "CAR",
  "CHI",
  "CIN",
  "CLE",
  "DAL",
  "DEN",
  "DET",
  "GB",
  "HOU",
  "IND",
  "JAX",
  "KC",
  "LAC",
  "LAR",
  "LV",
  "MIA",
  "MIN",
  "NE",
  "NO",
  "NYJ",
  "NYG",
  "PHI",
  "PIT",
  "SF",
  "SEA",
  "TB",
  "TEN",
  "WAS",
];

export const btffRoster = [
  "GLANZER",
  "WELCH",
  "TAGS",
  "HICKS",
  "PROBERT",
  "POPACK",
  "BARCH",
  "FREY",
  "deRUBIO",
  "KAZIN",
  "BECKER",
  "DEUTSHE",
  // 'KLION',
  "MICHALIGA",
  "PERRAS",
  // 'KATZ',
];

export const beckerRoster = [
  "LEE",
  "JAY",
  "PIERCE",
  "ZOE",
  "FREDDY",
  "LISA",
  "MILES",
  "MAX",
  "ANDY",
  "STEVE",
  "JOSH",
  "BEN",
  "GHOST 1",
  "GHOST 2",
];

export const roster2019 = [
  {
    name: "FREY",
    team1: "NO",
    team2: "WAS",
    score1: 0,
    score2: 0,
    img1: "../../public/NO.gif",
    img2: "../../public/WAS.gif",
  },
  {
    name: "deRUBIO",
    team1: "JAX",
    team2: "LA",
    score1: 0,
    score2: 0,
    img1: "../../public/JAX.gif",
    img2: "../../public/LA.gif",
  },
  {
    name: "DEUTSHE",
    team1: "KC",
    team2: "CAR",
    score1: 0,
    score2: 0,
    img1: "../../public/KC.gif",
    img2: "../../public/CAR.gif",
  },
  {
    name: "BECKER",
    team1: "SEA",
    team2: "ATL",
    score1: 0,
    score2: 0,
    img1: "../../public/SEA.gif",
    img2: "../../public/ATL.gif",
  },
  {
    name: "HICKS",
    team1: "PIT",
    team2: "CIN",
    score1: 0,
    score2: 0,
    img1: "../../public/PIT.gif",
    img2: "../../public/CIN.gif",
  },
  {
    name: "KAZIN",
    team1: "NYG",
    team2: "DAL",
    score1: 0,
    score2: 0,
    img1: "../../public/NYG.gif",
    img2: "../../public/DAL.gif",
  },
  {
    name: "GLANZER",
    team1: "BAL",
    team2: "OAK",
    score1: 0,
    score2: 0,
    img1: "../../public/BAL.gif",
    img2: "../../public/OAK.gif",
  },
  {
    name: "PROBERT",
    team1: "HOU",
    team2: "GB",
    score1: 0,
    score2: 0,
    img1: "../../public/HOU.gif",
    img2: "../../public/GB.gif",
  },
  {
    name: "PERRAS",
    team1: "NYJ",
    team2: "DET",
    score1: 0,
    score2: 0,
    img1: "../../public/NYJ.gif",
    img2: "../../public/DET.gif",
  },
  {
    name: "TAGS",
    team1: "BUF",
    team2: "PHI",
    score1: 0,
    score2: 0,
    img1: "../../public/BUF.gif",
    img2: "../../public/PHI.gif",
  },
  {
    name: "MICHALIGA",
    team1: "IND",
    team2: "TEN",
    score1: 0,
    score2: 0,
    img1: "../../public/IND.gif",
    img2: "../../public/TEN.gif",
  },
  {
    name: "POPACK",
    team1: "DEN",
    team2: "NE",
    score1: 0,
    score2: 0,
    img1: "../../public/DEN.gif",
    img2: "../../public/NE.gif",
  },
  {
    name: "WELCH",
    team1: "TB",
    team2: "LAC",
    score1: 0,
    score2: 0,
    img1: "../../public/TB.gif",
    img2: "../../public/LAC.gif",
  },
  {
    name: "BARCH",
    team1: "CHI",
    team2: "CLE",
    score1: 0,
    score2: 0,
    img1: "../../public/CHI.gif",
    img2: "../../public/CLE.gif",
  },
];

export const becker2019 = [
  {
    name: "MAX",
    team1: "LA",
    team2: "CIN",
    score1: 0,
    score2: 0,
    img1: ".../../public/LA.gif",
    img2: ".../../public/CIN.gif",
  },
  {
    name: "GHOST 1",
    team1: "NYJ",
    team2: "BAL",
    score1: 0,
    score2: 0,
    img1: ".../../public/NYJ.gif",
    img2: ".../../public/BAL.gif",
  },
  {
    name: "ZOE",
    team1: "MIN",
    team2: "ARI",
    score1: 0,
    score2: 0,
    img1: ".../../public/MIN.gif",
    img2: ".../../public/ARI.gif",
  },
  {
    name: "JAY",
    team1: "OAK",
    team2: "ATL",
    score1: 0,
    score2: 0,
    img1: ".../../public/OAK.gif",
    img2: ".../../public/ATL.gif",
  },
  {
    name: "MILES",
    team1: "CAR",
    team2: "WAS",
    score1: 0,
    score2: 0,
    img1: ".../../public/CAR.gif",
    img2: ".../../public/WAS.gif",
  },
  {
    name: "LEE",
    team1: "CHI",
    team2: "KC",
    score1: 0,
    score2: 0,
    img1: ".../../public/CHI.gif",
    img2: ".../../public/KC.gif",
  },
  {
    name: "GHOST 2",
    team1: "DET",
    team2: "GB",
    score1: 0,
    score2: 0,
    img1: ".../../public/DET.gif",
    img2: ".../../public/GB.gif",
  },
  {
    name: "FREDDY",
    team1: "BUF",
    team2: "JAX",
    score1: 0,
    score2: 0,
    img1: ".../../public/BUF.gif",
    img2: ".../../public/JAX.gif",
  },
  {
    name: "PIERCE",
    team1: "PHI",
    team2: "SEA",
    score1: 0,
    score2: 0,
    img1: ".../../public/PHI.gif",
    img2: ".../../public/SEA.gif",
  },
  {
    name: "JOSH",
    team1: "CLE",
    team2: "NYG",
    score1: 0,
    score2: 0,
    img1: ".../../public/CLE.gif",
    img2: ".../../public/NYG.gif",
  },
  {
    name: "BEN",
    team1: "NO",
    team2: "HOU",
    score1: 0,
    score2: 0,
    img1: ".../../public/NO.gif",
    img2: ".../../public/HOU.gif",
  },
  {
    name: "ANDY",
    team1: "NE",
    team2: "IND",
    score1: 0,
    score2: 0,
    img1: ".../../public/NE.gif",
    img2: ".../../public/IND.gif",
  },
  {
    name: "STEVE",
    team1: "TEN",
    team2: "SF",
    score1: 0,
    score2: 0,
    img1: ".../../public/TEN.gif",
    img2: ".../../public/SF.gif",
  },
  {
    name: "LISA",
    team1: "DAL",
    team2: "LAC",
    score1: 0,
    score2: 0,
    img1: ".../../public/DAL.gif",
    img2: ".../../public/LAC.gif",
  },
];

export const btff2021 = [
  {
    name: "PROBERT",
    team1: "GB",
    team2: "BUF",
    score1: 14,
    score2: 41,
    img1: "../../public/GB.gif",
    img2: "../../public/BUF.gif",
  },
  {
    name: "BARCH",
    team1: "NE",
    team2: "BAL",
    score1: 35,
    score2: 20,
    img1: "../../public/NE.gif",
    img2: "../../public/BAL.gif",
  },
  {
    name: "PERRAS",
    team1: "DEN",
    team2: "CLE",
    score1: 30,
    score2: 17,
    img1: "../../public/DEN.gif",
    img2: "../../public/CLE.gif",
  },
  {
    name: "POPACK",
    team1: "PIT",
    team2: "JAX",
    score1: 26,
    score2: 21,
    img1: "../../public/PIT.gif",
    img2: "../../public/JAX.gif",
  },
  {
    name: "BECKER",
    team1: "NYG",
    team2: "TEN",
    score1: 13,
    score2: 34,
    img1: "../../public/NYG.gif",
    img2: "../../public/TEN.gif",
  },

  {
    name: "TAGS",
    team1: "MIN",
    team2: "MIA",
    score1: 10,
    score2: 37,
    img1: "../../public/MIN.gif",
    img2: "../../public/MIA.gif",
  },

  {
    name: "MICHALIGA",
    team1: "BUF",
    team2: "CAR",
    score1: 41,
    score2: 3,
    img1: "../../public/BUF.gif",
    img2: "../../public/CAR.gif",
  },
  {
    name: "DeRUBIO",
    team1: "DET",
    team2: "HOU",
    score1: 20,
    score2: 20,
    img1: "../../public/DET.gif",
    img2: "../../public/HOU.gif",
  },

  {
    name: "CASCA",
    team1: "CIN",
    team2: "ATL",
    score1: 17,
    score2: 17,
    img1: "../../public/CIN.gif",
    img2: "../../public/ATL.gif",
  },

  {
    name: "RUSSO",
    team1: "SF",
    team2: "CHI",
    score1: 15,
    score2: 15,
    img1: "../../public/SF.gif",
    img2: "../../public/CHI.gif",
  },
  {
    name: "KAZIN",
    team1: "LAC",
    team2: "OAK",
    score1: 10,
    score2: 17,
    img1: "../../public/LAC.gif",
    img2: "../../public/OAK.gif",
  },

  {
    name: "GLANZER",
    team1: "ARI",
    team2: "DAL",
    score1: 10,
    score2: 14,
    img1: "../../public/ARI.gif",
    img2: "../../public/DAL.gif",
  },

  {
    name: "FREY",
    team1: "NYJ",
    team2: "PHI",
    score1: 23,
    score2: 0,
    img1: "../../public/NYJ.gif",
    img2: "../../public/PHI.gif",
  },

  {
    name: "WELCH",
    team1: "SEA",
    team2: "WAS",
    score1: 3,
    score2: 17,
    img1: "../../public/SEA.gif",
    img2: "../../public/WAS.gif",
  },
];

export const results2021 = [
  {
    name: "WELCH",
    team1: "GB",
    team2: "CAR",
    score1: 0,
    score2: 0,
    img1: "../../public/GB.gif",
    img2: "../../public/CAR.gif",
  },
  {
    name: "PERRAS",
    team1: "BUF",
    team2: "JAX",
    score1: 0,
    score2: 0,
    img1: "../../public/BUF.gif",
    img2: "../../public/JAX.gif",
  },
  {
    name: "PIERCE",
    team1: "NYG",
    team2: "KC",
    score1: 0,
    score2: 0,
    img1: "../../public/NYG.gif",
    img2: "../../public/KC.gif",
  },
  {
    name: "JOSH",
    team1: "SEA",
    team2: "PIT",
    score1: 0,
    score2: 0,
    img1: "../../public/SEA.gif",
    img2: "../../public/PIT.gif",
  },
  {
    name: "BEN",
    team1: "IND",
    team2: "DAL",
    score1: 0,
    score2: 0,
    img1: "../../public/IND.gif",
    img2: "../../public/DAL.gif",
  },
  {
    name: "LISA",
    team1: "CLE",
    team2: "DET",
    score1: 0,
    score2: 0,
    img1: "../../public/CLE.gif",
    img2: "../../public/DET.gif",
  },
  {
    name: "JAY",
    team1: "NE",
    team2: "MIN",
    score1: 0,
    score2: 0,
    img1: "../../public/NE.gif",
    img2: "../../public/MIN.gif",
  },
  {
    name: "ZOE",
    team1: "CIN",
    team2: "NYJ",
    score1: 13,
    score2: 0,
    img1: "../../public/CIN.gif",
    img2: "../../public/NYJ.gif",
  },
  {
    name: "FREDDY",
    team1: "OAK",
    team2: "BAL",
    score1: 0,
    score2: 0,
    img1: "../../public/OAK.gif",
    img2: "../../public/BAL.gif",
  },
  {
    name: "MAX",
    team1: "PHI",
    team2: "SF",
    score1: 0,
    score2: 0,
    img1: "../../public/PHI.gif",
    img2: "../../public/SF.gif",
  },
  {
    name: "STEVE",
    team1: "ATL",
    team2: "HOU",
    score1: 0,
    score2: 0,
    img1: "../../public/ATL.gif",
    img2: "../../public/HOU.gif",
  },
  {
    name: "LEE",
    team1: "MIA",
    team2: "WAS",
    score1: 0,
    score2: 0,
    img1: "../../public/MIA.gif",
    img2: "../../public/WAS.gif",
  },
];

export const becker2021 = [
  {
    name: "ANDY",
    team1: "GB",
    team2: "CAR",
    score1: 0,
    score2: 0,
    img1: "../../public/GB.gif",
    img2: "../../public/CAR.gif",
  },
  {
    name: "MILES",
    team1: "BUF",
    team2: "JAX",
    score1: 0,
    score2: 0,
    img1: "../../public/BUF.gif",
    img2: "../../public/JAX.gif",
  },
  {
    name: "PIERCE",
    team1: "NYG",
    team2: "KC",
    score1: 0,
    score2: 0,
    img1: "../../public/NYG.gif",
    img2: "../../public/KC.gif",
  },
  {
    name: "JOSH",
    team1: "SEA",
    team2: "PIT",
    score1: 0,
    score2: 0,
    img1: "../../public/SEA.gif",
    img2: "../../public/PIT.gif",
  },
  {
    name: "BEN",
    team1: "IND",
    team2: "DAL",
    score1: 0,
    score2: 0,
    img1: "../../public/IND.gif",
    img2: "../../public/DAL.gif",
  },
  {
    name: "LISA",
    team1: "CLE",
    team2: "DET",
    score1: 0,
    score2: 0,
    img1: "../../public/CLE.gif",
    img2: "../../public/DET.gif",
  },
  {
    name: "JAY",
    team1: "NE",
    team2: "MIN",
    score1: 0,
    score2: 0,
    img1: "../../public/NE.gif",
    img2: "../../public/MIN.gif",
  },
  {
    name: "ZOE",
    team1: "CIN",
    team2: "NYJ",
    score1: 0,
    score2: 0,
    img1: "../../public/CIN.gif",
    img2: "../../public/NYJ.gif",
  },
  {
    name: "FREDDY",
    team1: "OAK",
    team2: "BAL",
    score1: 0,
    score2: 0,
    img1: "../../public/OAK.gif",
    img2: "../../public/BAL.gif",
  },
  {
    name: "MAX",
    team1: "PHI",
    team2: "SF",
    score1: 0,
    score2: 0,
    img1: "../../public/PHI.gif",
    img2: "../../public/SF.gif",
  },
  {
    name: "STEVE",
    team1: "ATL",
    team2: "HOU",
    score1: 0,
    score2: 0,
    img1: "../../public/ATL.gif",
    img2: "../../public/HOU.gif",
  },
  {
    name: "LEE",
    team1: "MIA",
    team2: "WAS",
    score1: 0,
    score2: 0,
    img1: "../../public/MIA.gif",
    img2: "../../public/WAS.gif",
  },
];

export const becker2022 = [
  {
    name: "ANDY",
  },
  {
    name: "BEN",
  },
  {
    name: "FREDDY",
  },
  {
    name: "JAY",
  },
  {
    name: "JOSH",
  },
  {
    name: "LEE",
  },
  {
    name: "LISA",
  },
  {
    name: "MAX",
  },
  {
    name: "MILES",
  },
  {
    name: "PIERCE",
  },
  {
    name: "STEVE",
  },
  {
    name: "ZOE",
  },
];

export const btff2022 = [
  {
    name: "BARCH",
  },
  {
    name: "BECKER",
  },
  {
    name: "CASCA",
  },
  {
    name: "DeRUBIO",
  },
  {
    name: "FREY",
  },
  {
    name: "GLANZER",
  },
  {
    name: "KAZIN",
  },
  {
    name: "MICHALIGA",
  },
  {
    name: "PERRAS",
  },
  {
    name: "POPACK",
  },
  {
    name: "RUSSO",
  },
  {
    name: "PROBERT",
  },
  {
    name: "TAGS",
  },
  {
    name: "WELCH",
  },
];
